name: check_file_before_push

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  EXECUTABLES: "raytracer"

jobs:
  detect_o_files:
    runs-on: ubuntu-latest
    name: detect .o files push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0
      - name: check .o files push
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.o$' || true)
          if [ -n "$files" ]; then
            echo "You push .o file"
            echo "$files"
            exit 1
          else
            echo "It's ok"
          fi

  detect_executables:
    needs: detect_o_files
    runs-on: ubuntu-latest
    name: Executables detected
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if executables were pushed
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          failed=0
          for exe in $EXECUTABLES; do
            if echo "$files" | grep "$exe"; then
              echo "Executable $exe was pushed!"
              failed=1
            fi
          done
          if [ $failed -eq 1 ]; then
            exit 1
          else
            echo "No executables pushed."
          fi

  check_program_compilation:
    needs: detect_executables
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Compilation Check
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with make
        run: mkdir build

      - name: go in folder
        run: cd build

      - name: create cmake
        run: cmake -S ../ -B .

      - name: go to root
        run: cd ..

      - name: cmake executable
        run: cmake --build build/

      - name: Check executables exist and are executable
        run: |
          for file in $EXECUTABLES; do
            if [ ! -f "$file" ]; then
              echo "$file does not exist"
              exit 1
            fi
            if [ ! -x "$file" ]; then
              echo "$file is not executable"
              exit 1
            fi
          done