name: check_file_before_push

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  EXECUTABLES: "raytracer"

jobs:
  detect_o_files:
    runs-on: ubuntu-latest
    name: detect .o files push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0
      - name: check .o files push
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.sha }} | grep '\.o$' || true)
          if [ -n "$files" ]; then
            echo "You push .o file"
            echo "$files"
            exit 1
          else
            echo "It's ok"
          fi

  detect_executables:
    needs: detect_o_files
    runs-on: ubuntu-latest
    name: Executables detected
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if executables were pushed
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.sha }})
          failed=0
          for exe in $EXECUTABLES; do
            if echo "$files" | grep "$exe"; then
              echo "Executable $exe was pushed!"
              failed=1
            fi
          done
          if [ $failed -eq 1 ]; then
            exit 1
          else
            echo "No executables pushed."
          fi
